[Addon]
Name=fcitx-voicetype
GeneralName=VoiceType
GeneralName[zh_CN]=VoiceType 语音输入
Comment=VoiceType ASR bridge addon for Fcitx4
Comment[zh_CN]=基于 VoiceType ASR 服务的 Fcitx4 语音输入插件
Category=Module
Enabled=True
Library=fcitx-voicetype.so
Type=SharedLibrary
Priority=40
